name: Certora Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  certora_run_submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86"
      - run: cargo +1.86 install cargo-certora-sbf
      - run: cargo certora-sbf --no-build
      - name: Submit verification jobs to Certora Prover
        uses: Certora/certora-run-action@v1
        with:
          configurations: |-
            integrity.conf
            vault_consistency.conf
            no_dilution_processor.conf
            solvency_processor.conf
            fees.conf
            inflation.conf
          job-name: "Test Action"
          ecosystem: solana
          working-directory: programs/vault/src/certora/confs
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
